### ISSUE TITLE
cors error 

### ISSUE THREAD

**Issue by soniapello** [jrlarsen/react-hooks-in-action#5]
Hi John 
Do you have any idea on how I can fix cors request. I've tried many thing that I found on stackoverflow but nothing works
![error](https://user-images.githubusercontent.com/20027271/117252285-06cd6580-ae46-11eb-9216-474be9f022d8.jpg)

**Comment by jrlarsen** [comment]
It's hard to tell from what you've posted. What code are you using to fetch the users? Are you specifying the full URL? Is this from a particular branch in the original repo or have you coded it yourself?

**Comment by soniapello** [comment]
I'm using the last branch [1306-suspense-list](https://github.com/jrlarsen/react-hooks-in-action/tree/1306-suspense-list). 
I didn't change or code anything.
I've bought a javascript book from you and I like it. I'm trying to learn react hooks and I've seen you publish a book on react hooks recently so I just want to see a live version of the app before buying the book. 
Maybe you have a link where we can see the final version of the app.
It may sound strange but I like to see what I will be building before starting a book.

**Comment by jrlarsen** [comment]
Ah, you need to start the json database server as well as running npm start:
`json-server --watch db.json --port 3001`
