### ISSUE TITLE
branch 0204 set index doesn't seem to work

### ISSUE THREAD

**Issue by country-bumpkin-software** [jrlarsen/react-hooks-in-action#8]
When I use branch 2040-set-index I get the following error:

ERROR in ./src/components/Bookables/BookablesList.js 13:27-43
export 'bookables'.'filter' (imported as 'bookables') was not found in '../../static.json' (possible exports: 0, 1, 2, 3, 4, 5)
 @ ./src/components/Bookables/BookablesPage.js 4:0-44 9:35-48
 @ ./src/components/App.js 7:0-54 124:40-53
 @ ./src/index.js 5:0-38 7:38-41

ERROR in ./src/components/Bookables/BookablesList.js 15:14-23
Should not import the named export 'bookables' (imported as 'bookables') from default-exporting module (only default export is available soon)
 @ ./src/components/Bookables/BookablesPage.js 4:0-44 9:35-48
 @ ./src/components/App.js 7:0-54 124:40-53
 @ ./src/index.js 5:0-38 7:38-41

webpack 5.66.0 compiled with 2 errors in 102 ms

**Comment by country-bumpkin-software** [comment]
I had to change the code as follows:
```
import {useState} from 'react';
const data = require('../../static.json')

export default function BookablesList () {
    console.log(data);
  const group = "Rooms";

  const bookablesInGroup = data.bookables.filter(b => b.group === group);
  const [bookableIndex, setBookableIndex] = useState(1);
    console.log(data);
  return (
    <ul className="bookables items-list-nav">
      {bookablesInGroup.map((b, i) => (
        <li
          key={b.id}
          className={i === bookableIndex ? "selected" : null}
        >
          <button
            className="btn"
            onClick={() => setBookableIndex(i)}
          >
            {b.title}
          </button>
        </li>
      ))}
    </ul>
  );
}
```

**Comment by mortenbrudvik** [comment]
This worked for me
```js
import data from "../../static.json";

export default function BookablesList () {

  const group = "Rooms";

  const bookablesInGroup = data.bookables.filter(b => b.group === group);
```
